config/routes.rb
Rails.application.routes.draw do
  resources :books, only: [:index, :create, :new, :edit, :show, :update]
  resources :report, only: [:index]
  root 'books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books
  validates_uniqueness_of :name
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :format
  has_and_belongs_to_many :authors
  validates_presence_of :title, :release_date, :authors
  validate :base_price_based_on_release_date

  scope :published_2018, -> { 
    where('release_date > ?', DateTime.new(2017, 12, 31))
    .where('release_date < ?', DateTime.new(2018, 12, 31))
  }
  scope :by_format, -> (format) { where(format_id: format.id) }

  protected

  def base_price_based_on_release_date
    unless release_date.nil?
      two_months_from_now = DateTime.now + 2.month
      if base_price.nil? && release_date <= two_months_from_now && release_date > DateTime.now
        errors.add(:base_price, 'required if release date is within 2 months')
      end
    end
  end
end

app/models/format.rb
class Format < ApplicationRecord
  has_one :book
  validates_uniqueness_of :name
  validate :correct_name

  protected

  def correct_name
    unless ['Digital', 'Hardcover', 'Softcover'].include? name
      errors.add(:name, 'invalid - must be Digital, Hardcover, or Softcover')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update]

  # GET /books
  def index
    @books = Book.all
  end

  # GET /books/1
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @book.format = Format.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = Book.new(book_params)
    if params.has_key? 'author_id'
      params[:author_id].each do |i|
        author = Author.find(i)
        @book.authors << author
      end  
    end
    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  def update
    if params.has_key? 'author_id'
      @book.authors = []
      params[:author_id].each do |i|
        author = Author.find(i)
        @book.authors << author
      end  
    end
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'      
    else
      render :edit        
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.permit(:title, :release_date, :format_id, :base_price)
    end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def index
    fmt = Format.find_by(name: "Hardcover")
    @books = Book.published_2018.by_format(fmt)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/books/edit.html.erb
<h1>Editing <%= @book.title %></h1>
<hr />
<%= form_with(model: @book, local: true) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= label_tag :title %>
    <%= text_field_tag :title, @book.title %>
  </div>

  <div>
    <%= label_tag :author_id %>
    <%= select_tag :author_id, 
      options_from_collection_for_select(Author.all, 'id', 'name', @book.authors.map(&:id)),   
      multiple: true %>  
  </div>

  <div>
    <%= label_tag :release_date, 'Release date (YYYY-MM-DD)' %>
    <%= text_field_tag :release_date, @book.release_date.strftime("%Y-%m-%d") %>
  </div>

  <div>
    <%= label_tag :base_price %>
    <%= text_field_tag :base_price, @book.base_price %>
  </div>

  <div>
    <%= label_tag :format_id %>
    <%= select_tag :format_id, 
      options_from_collection_for_select(Format.all, 'id', 'name', @book.format.id), 
      include_blank: 'Select format...' %>  
  </div>

  <div class="actions">
    <%= form.submit 'Update Book', class: "button alert" %>
    <%= link_to 'Return to book list', books_path, class: "button success" %>
  </div>
<% end %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>
<hr />
<% if @books.present? %>
<table>
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<%= link_to 'Create a new book', new_book_path, class: "button alert" %>
<%= link_to 'View report', report_index_path, class: "button success"  %> 

app/views/books/new.html.erb
<h1>New Book</h1>
<hr />
<%= form_with(model: @book, local: true) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= label_tag :title %>
    <%= text_field_tag :title %>
  </div>

  <div>
    <%= label_tag :author_id %>
    <%= select_tag :author_id, 
      options_from_collection_for_select(Author.all, 'id', 'name'),   
      multiple: true %>  
  </div>

  <div>
    <%= label_tag :release_date, 'Release date (YYYY-MM-DD)' %>
    <%= text_field_tag :release_date %>
  </div>

  <div>
    <%= label_tag :base_price %>
    <%= text_field_tag :base_price %>
  </div>

  <div>
    <%= label_tag :format_id %>
    <%= select_tag :format_id, 
      options_from_collection_for_select(Format.all, 'id', 'name'), 
      include_blank: 'Select format...' %>  
  </div>

  <div class="actions">
    <%= form.submit 'Create Book', class: 'button alert' %>
    <%= link_to 'Return to book list', books_path, class: "button success" %>
  </div>
<% end %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Product details for <%= @book.title %></h1>
<hr />
<table>
<thead>
  <tr>
    <th width="30%">Title</th>
    <th width="30%">Author(s)</th>
    <th width="15%">Format</th>
    <th width="15%">Release Date</th>
    <th width="10%">Base Price</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><%= @book.title %></td>
    <td><%= @book.authors.map(&:name).join(', ') %></td>
    <td><%= @book.format.name %></td>
    <td><%= @book.release_date.strftime("%B %e, %Y") %></td>
    <td><%= number_to_currency @book.base_price %></td>
  </tr>
</tbody>
</table>

<%= link_to 'Edit this book', edit_book_path(@book), class: "button alert" %>
<%= link_to 'Return to book list', books_path, class: "button success" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>CPG Example App</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/report/index.html.erb
<h1>Hardcover books published in 2018</h1>
<hr />
<% if @books.present? %>
<table>
<thead>
  <tr>
    <th>Title</th>
    <th>Release Date</th>
  </tr>
</thead>
<tbody>  
  <% @books.each do |book| %>
    <tr>
      <td><%= link_to book.title, book %></td>
      <td><%= book.release_date.strftime("%B %e, %Y") %></td>
    </tr>
  <% end %>
</tbody>  
</table>
<% end %>

<%= link_to 'Return to book list', books_path, class: "button success" %>